### ISSUE TITLE
undefined variable in curl command downloading  onboot - package

### ISSUE THREAD

**Issue by chrisstinemetz** [mabunixda/ansible-udmp#5]
`onboot_version` dict object does not have the attribute `stdout` when query package version play is ran. I think the command's output isn't getting captured because `podman` exec isn't exiting cleanly. 

I tested directly on udmpro CLI and here are the results:

``` bash
# podman exec -it unifi-os dpkg-query --showformat='${Version}' --show udm-boot
dpkg-query: no packages found matching udm-boot
Error: non zero exit code: 1: OCI runtime error
#
```

unifi_onboot_download_uri is not defined in `tasks/onboot.yml` for play `onboot - download package` . I believe the variable should be initialized to: `https://udm-boot.boostchicken.dev`. I can make a pull request if you like.

**Comment by mabunixda** [comment]
The variable ```onboot_version``` should contain the current installed version, but if the command fails, the variable is not registered. this should be fixed with [this commit](https://github.com/mabunixda/ansible-udmp/commit/c4ca4a6f1548a1a7c61ecabbe3d96dc8697b5121)

**Comment by mabunixda** [comment]
@chrisstinemetz so the issue should be fixed now.

If you want to update the udm boot version to 1.0.5-fix you have to define a playbook like this one:
```
---
- name: udmp setup
  hosts: < UNIFI_UDM_HOSTNAME >
  gather_facts: false
  roles:
    - role: udmp
      udm_onboot_version: 1.0.5
      udm_onboot_download_uri: "https://github.com/boostchicken/udm-utilities/releases/download/1.0.5-fix/udm-boot_1.0.5_all.deb"
```
